version: "3.9"

services:
  mail:
    container_name: mail_container
    env_file: .env
    build: ./email_api
    ports: 
      - "8001:8001"
  api:
    container_name: api_container
    build: ./transapp
    volumes:
      - .:/code
    # env_file: .env
    ports: 
      - "8000:8000"
