version: "3.9"

services:
  mail:
    container_name: mail_cont
    env_file: .env
    build: ./email_api
    ports: 
      - "8001:8001"
  api:
    container_name: api_cont
    build: .
    volumes:
      - .:/code
    env_file: .env
    ports: 
      - "8000:8000"
    command: gunicorn transapp.wsgi:application -w 2 --bind 0.0.0.0:8000 --reload
