version: "3.9"

services:

  mail:
    container_name: mail_container
    env_file: .env
    build: ./email_api
    working_dir: /email_api
    volumes:
      - ./email_api:/email_api
    ports:
      - "8001:8001"
    command: uvicorn send_email:app --port 8001 --host 0.0.0.0 --reload

  redis:
    image: redis:6.2-alpine

  celery_worker:
    container_name: celery_worker
    build: ./email_api
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ./email_api:/email_api
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - mail
      - redis

  flower:
    container_name: flower
    build: ./email_api
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - mail
      - redis
      - celery_worker


  api:
    container_name: api_container
    build: ./transapp
    environment:
      - DB_HOST=db
      - DB_NAME=post_db
      - DB_USER=post_miska
      - DB_PASS=123
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./transapp:/code
    command: bash -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "

  db:
    container_name: db_container
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=post_db
      - POSTGRES_USER=post_miska
      - POSTGRES_PASSWORD=123
    volumes:
      - ./my-db2:/var/lib/pgsql/data

volumes:
  my-db2:
