# Generated by Django 4.0.5 on 2022-07-25 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_receiveaction_time_delta_and_more'),
        ('core', '0003_user_warehouse_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='storage.warehouse'),
        ),
    ]
