# Generated by Django 4.0.5 on 2022-08-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
