# Generated by Django 4.0.5 on 2022-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('USR', 'User'), ('WHR', 'Warehouser'), ('DIR', 'Director')], default='USR', max_length=255),
        ),
    ]
