# Generated by Django 4.0.5 on 2022-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('WHR', 'Warehouser'), ('DIR', 'Director'), ('ADM', 'Admin'), ('COR', 'Coordinator')], default='WHR', max_length=255),
        ),
    ]
