# Generated by Django 4.0.5 on 2022-08-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_action_action_id_action_date'),
        ('core', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='storage.warehouse'),
        ),
    ]
