# Generated by Django 4.0.5 on 2022-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('USR', 'User'), ('WHR', 'Warehouser'), ('DIR', 'Director'), ('ADM', 'Admin')], default='USR', max_length=255),
        ),
    ]
