# Generated by Django 4.0.5 on 2022-08-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('action_type', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255)),
                ('status', models.CharField(choices=[('delivered_broken', 'Delivered with broken products'), ('delivered', 'Delivered with no problems'), ('in_progress', 'In progress'), ('unready', 'Not ready to action')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OpenningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timespan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('monthday', models.DateField()),
                ('action', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('action_available', models.ManyToManyField(blank=True, related_name='warehouse_action', to='storage.timespan')),
                ('openning_time', models.ManyToManyField(to='storage.openningtime')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timespan',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='timespan_check_hours'),
        ),
        migrations.AddConstraint(
            model_name='openningtime',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='openningtime_check_hours'),
        ),
        migrations.AddField(
            model_name='action',
            name='transport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='transport.transport'),
        ),
        migrations.AddField(
            model_name='action',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse'),
        ),
        migrations.AddField(
            model_name='action',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
