# Generated by Django 4.0.5 on 2022-08-16 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openning_time', to='storage.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('monthday', models.DateField()),
                ('action_type', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_window', to='storage.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('action_type', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('delivered_broken', 'Delivered with broken products'), ('delivered', 'Delivered with no problems'), ('in_progress', 'In progress'), ('unready', 'Not ready to action')], max_length=25)),
                ('action_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='storage.actionwindow')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='transport.transport')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='storage.warehouse')),
                ('workers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='openningtime',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='openningtime_check_hours'),
        ),
        migrations.AddConstraint(
            model_name='actionwindow',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='actionwindow_check_hours'),
        ),
    ]
