# Generated by Django 4.0.5 on 2022-08-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timespan',
            name='action',
        ),
    ]
