# Generated by Django 4.0.5 on 2022-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveaction',
            name='id_offer',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendaction',
            name='id_offer',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default=12345, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
