# Generated by Django 4.0.5 on 2022-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_receiveaction_id_offer_sendaction_id_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='receive_time',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='send_time',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='receive_available',
            field=models.ManyToManyField(blank=True, null=True, related_name='warehouse_receive', to='storage.timespan'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='send_available',
            field=models.ManyToManyField(blank=True, null=True, related_name='warehouse_send', to='storage.timespan'),
        ),
    ]
