# Generated by Django 4.0.5 on 2022-08-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_timespan_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespan',
            name='action',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], default='send', max_length=255),
            preserve_default=False,
        ),
    ]
