# Generated by Django 4.0.5 on 2022-08-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_action_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
