# Generated by Django 4.0.5 on 2022-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_action_duration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('duration__isnull', False), ('status', 'delivered')), models.Q(('duration__isnull', False), ('status', 'delivered_broken')), models.Q(('duration__isnull', True), ('status', 'in_progress')), _connector='OR'), name='check_duration_correct'),
        ),
    ]
