# Generated by Django 4.0.5 on 2022-08-06 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_timespan_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timespan',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='timespan',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='storage.timespan'),
            preserve_default=False,
        ),
    ]
