# Generated by Django 4.0.5 on 2022-08-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_timespan_action_action_timespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespan',
            name='action_type',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], default='send', max_length=255),
            preserve_default=False,
        ),
    ]
