# Generated by Django 4.0.5 on 2022-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_warehouse_receive_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveaction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sendaction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
