# Generated by Django 4.0.5 on 2022-08-27 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_remove_action_check_duration_correct_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='action',
            name='check_duration_correct',
        ),
        migrations.AlterField(
            model_name='action',
            name='workers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('duration__isnull', False), ('status', 'delivered')), models.Q(('duration__isnull', False), ('status', 'delivered_broken')), models.Q(('duration__isnull', True), ('status', 'in_progress')), models.Q(('duration__isnull', True), ('status', 'unready'), ('warehouse__isnull', True)), _connector='OR'), name='check_status_correct'),
        ),
    ]
