# Generated by Django 4.0.5 on 2022-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_receiveaction_description_sendaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openningtime',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
    ]
