# Generated by Django 4.0.5 on 2022-08-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_timespan_action_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='action_available',
            new_name='timespan_available',
        ),
    ]
