# Generated by Django 4.0.5 on 2022-08-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_rename_action_available_warehouse_timespan_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='timespan_available',
            field=models.ManyToManyField(blank=True, related_name='warehouse', to='storage.timespan'),
        ),
    ]
