# Generated by Django 4.0.5 on 2022-08-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_action_check_duration_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionwindow',
            name='action_type',
        ),
    ]
