# Generated by Django 4.0.5 on 2022-07-25 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_openningtime_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveaction',
            name='time_delta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.timedelta'),
        ),
        migrations.AlterField(
            model_name='sendaction',
            name='time_delta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='storage.timedelta'),
        ),
    ]
