# Generated by Django 4.0.5 on 2022-08-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_actionwindow_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_window',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='storage.actionwindow'),
        ),
    ]
