# Generated by Django 4.0.5 on 2022-07-25 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_receiveaction_time_delta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveaction',
            name='time_delta',
        ),
        migrations.RemoveField(
            model_name='sendaction',
            name='time_delta',
        ),
        migrations.AddField(
            model_name='receiveaction',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='sendaction',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
