# Generated by Django 4.0.5 on 2022-08-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_warehouse_timespan_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='timespan_available',
        ),
        migrations.AddField(
            model_name='timespan',
            name='warehouse',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, related_name='timespan_available', to='storage.warehouse'),
            preserve_default=False,
        ),
    ]
