# Generated by Django 4.0.5 on 2022-08-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_warehouse_timespan_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='storage.warehouse'),
        ),
    ]
