# Generated by Django 4.0.5 on 2022-07-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_remove_receiveaction_time_delta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timespan',
            old_name='month_day',
            new_name='monthday',
        ),
    ]
