# Generated by Django 4.0.5 on 2022-08-01 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions
import storage.constants
import uuid


class Migration(migrations.Migration):

    replaces = [('storage', '0010_remove_receiveaction_warehouse_and_more'), ('storage', '0011_rename_sendaction_action_and_more'), ('storage', '0012_timespan_action'), ('storage', '0013_alter_action_id_offer'), ('storage', '0014_alter_action_action_type_alter_timespan_action'), ('storage', '0015_alter_timespan_action'), ('storage', '0016_alter_timespan_action'), ('storage', '0017_alter_action_action_type'), ('storage', '0018_timespan_check_hours'), ('storage', '0019_remove_timespan_check_hours_and_more'), ('storage', '0020_alter_action_id_offer'), ('storage', '0021_alter_action_id_offer'), ('storage', '0022_remove_action_description_and_more')]

    dependencies = [
        ('storage', '0009_rename_month_day_timespan_monthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveaction',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='receiveaction',
            name='workers',
        ),
        migrations.DeleteModel(
            name='Timedelta',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='receive_available',
        ),
        migrations.AddField(
            model_name='sendaction',
            name='action',
            field=models.CharField(default='send', max_length=20),
        ),
        migrations.DeleteModel(
            name='ReceiveAction',
        ),
        migrations.RenameModel(
            old_name='SendAction',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='action_type',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='send_available',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='action_available',
            field=models.ManyToManyField(blank=True, related_name='warehouse_action', to='storage.timespan'),
        ),
        migrations.AlterField(
            model_name='action',
            name='id_offer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(default='send', max_length=255),
        ),
        migrations.AddField(
            model_name='timespan',
            name='action',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='timespan',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='check_hours'),
        ),
        migrations.RemoveConstraint(
            model_name='timespan',
            name='check_hours',
        ),
        migrations.AddConstraint(
            model_name='openningtime',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='openningtime_check_hours'),
        ),
        migrations.AddConstraint(
            model_name='timespan',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='timespan_check_hours'),
        ),
        migrations.AlterField(
            model_name='action',
            name='id_offer',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='id_offer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='action',
            name='description',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='description',
        ),
    ]
