# Generated by Django 4.0.5 on 2022-07-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_rename_month_day_timespan_monthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiveaction',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='receiveaction',
            name='workers',
        ),
        migrations.DeleteModel(
            name='Timedelta',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='receive_available',
        ),
        migrations.AddField(
            model_name='sendaction',
            name='action',
            field=models.CharField(default='send', max_length=20),
        ),
        migrations.DeleteModel(
            name='ReceiveAction',
        ),
    ]
