# Generated by Django 4.0.5 on 2022-08-14 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_action_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('monthday', models.DateField()),
                ('action_type', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='timespan',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='openning_time',
        ),
        migrations.AddField(
            model_name='openningtime',
            name='warehouse',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='openning_time', to='storage.warehouse'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Timespan',
        ),
        migrations.AddField(
            model_name='actionwindow',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_window', to='storage.warehouse'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_window',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='storage.actionwindow'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='actionwindow',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='actionwindow_check_hours'),
        ),
    ]
