# Generated by Django 4.0.5 on 2022-07-27 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0010_remove_receiveaction_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendAction',
            new_name='Action',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='action_type',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='send_available',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='action_available',
            field=models.ManyToManyField(blank=True, related_name='warehouse_action', to='storage.timespan'),
        ),
    ]
