# Generated by Django 4.0.5 on 2022-08-15 17:44

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_actionwindow_remove_action_timespan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='action',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
