# Generated by Django 4.0.5 on 2022-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_rename_sendaction_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timespan',
            name='action',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], default='send', max_length=25),
            preserve_default=False,
        ),
    ]
