# Generated by Django 4.0.5 on 2022-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_warehouse_openning_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='openning_time',
            field=models.ManyToManyField(to='storage.openningtime'),
        ),
    ]
