# Generated by Django 4.0.5 on 2022-08-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_order_order_id'),
        ('storage', '0011_action_action_id_action_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='storage.actionwindow'),
        ),
        migrations.AlterField(
            model_name='action',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='transport.transport'),
        ),
    ]
