# Generated by Django 4.0.5 on 2022-07-28 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_timespan_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id_offer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
