# Generated by Django 4.0.5 on 2022-07-28 19:32

from django.db import migrations, models
import storage.constants


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_alter_action_id_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(default=storage.constants.TimespanActionEnum['SEND'], max_length=255),
        ),
        migrations.AlterField(
            model_name='timespan',
            name='action',
            field=models.CharField(choices=[('TimespanActionEnum.SEND', 'Send'), ('TimespanActionEnum.RECEIVE', 'Receive')], max_length=255),
        ),
    ]
