# Generated by Django 4.0.5 on 2022-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_action_action_type_alter_timespan_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='action',
            field=models.CharField(choices=[('SEND', 'Send'), ('RECEIVE', 'Receive')], max_length=25),
        ),
    ]
