# Generated by Django 4.0.5 on 2022-07-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_timespan_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timespan',
            name='action',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255),
        ),
    ]
