# Generated by Django 4.0.5 on 2022-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_alter_timespan_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=255),
        ),
    ]
