# Generated by Django 4.0.5 on 2022-08-01 12:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_timespan_check_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timespan',
            name='check_hours',
        ),
        migrations.AddConstraint(
            model_name='openningtime',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='openningtime_check_hours'),
        ),
        migrations.AddConstraint(
            model_name='timespan',
            constraint=models.CheckConstraint(check=models.Q(('from_hour__lt', django.db.models.expressions.F('to_hour'))), name='timespan_check_hours'),
        ),
    ]
