# Generated by Django 4.0.5 on 2022-08-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_remove_timespan_check_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id_offer',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
