# Generated by Django 4.0.5 on 2022-08-01 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_alter_action_id_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id_offer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
