# Generated by Django 4.0.5 on 2022-08-16 01:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=30, unique=True)),
                ('capacity', models.IntegerField()),
                ('is_refrigerate', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['is_available', '-capacity'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_refrigerate', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.route')),
                ('vehicle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='transport.transport')),
            ],
        ),
    ]
