# Generated by Django 4.0.5 on 2022-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedoffer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
