# Generated by Django 4.0.5 on 2022-08-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_order_broken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
