# Generated by Django 4.0.5 on 2022-07-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_acceptedoffer_description_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id_offer',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.DeleteModel(
            name='AcceptedOffer',
        ),
    ]
