# Generated by Django 4.0.5 on 2022-07-28 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_offer_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id_offer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
