# Generated by Django 4.0.5 on 2022-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_offer_id_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='route',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='description',
        ),
    ]
